image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - code_quality # List of stages for jobs, and their order of execution


.some-script-before: &some-script-before
    - python3 --version  # For debugging

"Ensure PEP8-compliancy":
  stage: code_quality
  before_script:
    - *some-script-before
  script:
    - /usr/lib/python3/dist-packages pycodestyle --ignore=E501 aras_all_in_one_.py

"Lint code with pylint":
  stage: code_quality
  before_script:
    - *some-script-before
  script:
    - /usr/lib/python3/dist-packages pylint --ignore=E501 aras_all_in_one_.py

"Run flake8":
  stage: code_quality
  before_script:
    - *some-script-before
  script:
    - /usr/lib/python3/dist-packages flake8 --ignore=E501 aras_all_in_one_.py

