image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - code_quality # List of stages for jobs, and their order of execution


.some-script-before: &some-script-before
    - python3 --version  # For debugging
    - pip install -r requirements.txt

"Ensure PEP8-compliancy":
  stage: code_quality
  before_script:
    - *some-script-before
  script:
    - pycodestyle --ignore=E501 src/*.py

"Lint code with pylint":
  stage: code_quality
  before_script:
    - *some-script-before
  script:
    - pylint --disable=C0301 --disable=R0801 src/*.py

"Run flake8":
  stage: code_quality
  before_script:
    - *some-script-before
  script:
    - flake8 --ignore=E501 src/*.py

