image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - code_quality # List of stages for jobs, and their order of execution


.some-script-before: &some-script-before
    - python --version  # For debugging

"Ensure PEP8-compliancy":
  stage: code_quality
  before_script:
    - *some-script-before
  script:
    - python3 -m pycodestyle --ignore=E501 src/*.py

"Lint code with pylint":
  stage: code_quality
  before_script:
    - *some-script-before
  script:
    - python3 -m pylint --ignore=E501 src/*.py

"Run flake8":
  stage: code_quality
  before_script:
    - *some-script-before
  script:
      python3 -m flake8 --ignore=E501 src/*.py

